namespace _4Time.FrontEnd
{
    internal class ProgrammingJoke
    {
        private static Random random = new Random();
        private static int autismCounter = 0;
        private static Dictionary<int, string> ProgrammingJokesDic = new Dictionary<int, string>
        {
            {1, "Warum hat der Programmierer seinen Job gekündigt? Weil er keine Arrays mochte."},
            {2, "Was ist der Lieblingsort eines Programmierers? Die Foo Bar."},
            {3, "Warum war der JavaScript-Entwickler traurig? Weil er keine 'Promises' hatte."},
            {4, "Wie viele Programmierer braucht man, um eine Glühbirne zu wechseln? Keinen, das ist ein Hardwareproblem."},
            {5, "Warum verwechseln Programmierer Halloween und Weihnachten? Weil Oct 31 == Dec 25."},
            {6, "Es gibt 10 Arten von Menschen auf der Welt: Diejenigen, die Binär verstehen, und diejenigen, die es nicht tun."},
            {7, "Warum war der Algorithmus so fit? Weil er viele 'log' Lifts gemacht hat."},
            {8, "Was sagt ein Programmierer, wenn er auf ein Problem stößt? 'Das ist ein Feature, kein Bug.'"},
            {9, "Warum hat der Debugger Schluss gemacht? Wegen zu vieler 'issues'."},
            {10, "Was ist das Motto eines Programmierers? 'Keep calm and code on.'"},
            {11, "Warum sind Programmierer so schlecht im Verstecken spielen? Weil sie immer im 'Log' sind."},
            {12, "Ein SQL-Query geht in eine Bar, sieht zwei Tabellen und fragt: 'Darf ich mich Ihnen anschließen?'"},
            {13, "Was ist die Lieblingsmusik eines Programmierers? Algo-rhythm and Blues."},
            {14, "Warum hat der CSS-Entwickler geweint? Wegen der 'Cascading Style Sadness'."},
            {15, "Was sagt ein Java-Entwickler, wenn er friert? 'Ich brauche mehr Wrappers.'"},
            {16, "Warum hat das Python-Programm kalte Füße bekommen? Wegen zu vieler 'Indentation Errors'."},
            {17, "Was ist der Unterschied zwischen HTML und HTML5? Etwa 5 Jahre."},
            {18, "Warum war die Datenbank so langsam? Weil sie zu viele 'relationships' hatte."},
            {19, "Was ist der beste Weg, um einen Programmierer zu erschrecken? Zeige ihm Code ohne Kommentare."},
            {20, "Warum sind Programmierer so gut in Escape Rooms? Weil sie ständig nach dem 'Ausgang' suchen."},
            {21, "Ein Programmierer geht in eine Bar und bestellt 1.0 Bier. Dann bestellt er 0.0 Bier. Dann bestellt er NaN Bier."},
            {22, "Was ist der Lieblings-Snack eines Programmierers? Ein Cookie."},
            {23, "Warum hat der C#-Entwickler eine Brille bekommen? Weil er nicht scharf sehen konnte."},
            {24, "Was sagt ein müder Programmierer? 'Ich brauche einen Reboot.'"},
            {25, "Warum mögen Programmierer keine Natur? Es hat zu viele Bugs."},
            {26, "Was ist der Lieblings-Sport eines Programmierers? Debugging."},
            {27, "Wie nennt man einen Programmierer aus Finnland? Nerdic."},
            {28, "Warum hat der Compiler gekündigt? Er hatte zu viele 'warnings'."},
            {29, "Was ist das Lieblings-Tier eines Programmierers? Ein Python."},
            {30, "Warum war der API so beliebt? Weil er gute 'connections' hatte."},
            {31, "Programmierer: 'Wir haben ein Problem.' Manager: 'Ist es reproduzierbar?' Programmierer: 'Ja.' Manager: 'Dann ist es kein Problem mehr.'"},
            {32, "Es gibt zwei schwierige Dinge in der Informatik: Cache-Invalidierung und Dinge benennen."},
            {33, "Was ist der Unterschied zwischen einem Programmierer und einem Softwareentwickler? Der Titel."},
            {34, "Warum hat der Computer eine Erkältung bekommen? Er hatte zu viele offene Fenster."},
            {35, "Was ist der Lieblingsfilm eines Programmierers? The Social Network."},
            {36, "Warum war der Code so schwer zu lesen? Er hatte zu viele 'nested loops'."},
            {37, "Was sagt ein Programmierer, wenn er überrascht ist? 'Syntax Error?!'"},
            {38, "Warum sind Programmierer wie Zauberer? Sie verwandeln Kaffee in Code."},
            {39, "Was ist das Lieblings-Dateiformat eines Programmierers? .json (gesprochen: Jason)."},
            {40, "Warum hat der Entwickler aufgehört, Schach zu spielen? Zu viele 'checkmates'."},
            {41, "Wie nennt man einen pessimistischen Programmierer? Einen Bug-Realisten."},
            {42, "Warum ging der Programmierer pleite? Wegen der 'NullPointerExceptions'."},
            {43, "Was ist das Lieblings-Frühstück eines Programmierers? Spam und Eggs (ohne das Spam)."},
            {44, "Warum können Programmierer schlecht lügen? Weil sie immer 'true' oder 'false' sagen."},
            {45, "Was macht ein Programmierer im Urlaub? 'git commit -m \"relaxing\"'."},
            {46, "Warum war der Binärbaum so nervös? Wegen seiner 'root' Probleme."},
            {47, "Was ist das Lieblings-Instrument eines Programmierers? Die Tastatur."},
            {48, "Warum hat der Programmierer den Kaffee verschüttet? Weil er einen 'Java' Fehler gemacht hat."},
            {49, "Was ist der Lieblings-Superheld eines Programmierers? Spider-Man (wegen des Webs)."},
            {50, "Warum hassen Programmierer die Natur? Zu viele 'Bäume' und 'Blätter' (nodes und leaves)."},
            {51, "Ein Bit fragt das andere: 'Geht's dir nicht gut?' Das andere Bit: 'Nein, ich fühle mich ein wenig off.'"},
            {52, "Was ist der Lieblings-Tanz eines Programmierers? Der Algo-Rhythmus."},
            {53, "Warum hat der Server eine Therapie gebraucht? Wegen zu vieler 'Requests'."},
            {54, "Was ist die Lieblings-Fernsehserie eines Programmierers? Mr. Robot."},
            {55, "Warum hat der Code eine Diät gemacht? Um 'lightweight' zu werden."},
            {56, "Wie debuggt ein römischer Programmierer? Mit 'console.log(X)'."},
            {57, "Warum war der Entwickler so gestresst? Wegen der 'Deadline'. Druck."},
            {58, "Was ist der Albtraum eines Programmierers? Ein 'infinite loop' im echten Leben."},
            {59, "Warum sind Java-Entwickler so gut im Vererben? Weil sie Klassen haben."},
            {60, "Was ist der Lieblings-Drink eines Programmierers? Ein 'Root'-Bier."},
            {61, "Warum hat das UI-Element geweint? Weil es keine 'Aufmerksamkeit' bekam."},
            {62, "Wie nennt man einen Programmierer, der keine Kommentare schreibt? Einen zukünftigen Arbeitslosen."},
            {63, "Warum war der Boolean so entscheidungsfreudig? Weil er nur zwei Optionen hatte."},
            {64, "Was ist der Unterschied zwischen einem Introvertierten und einem Extrovertierten Programmierer? Der Introvertierte schaut auf seine Schuhe, wenn er mit dir redet. Der Extrovertierte schaut auf *deine* Schuhe."},
            {65, "Warum hat der Programmierer eine Leiter mit zur Arbeit gebracht? Für die 'High-Level' Programmierung."},
            {66, "Was ist das Lieblings-Spielzeug eines Programmierers? Ein 'Raspberry Pi'."},
            {67, "Warum hat die Funktion aufgehört zu arbeiten? Sie hatte zu viele 'Argumente'."},
            {68, "Wie organisiert ein Programmierer eine Party? Mit 'Arrays' und 'Lists'."},
            {69, "Warum war der Programmierer so ruhig? Er war im 'Deep Thought'."},
            {70, "Was ist das Lieblings-Buch eines Programmierers? 'Clean Code'."},
            {71, "Warum hat der String den Integer verlassen? Er war nicht sein 'Typ'."},
            {72, "Was ist das Lieblings-Accessoire eines Programmierers? Ein USB-Stick."},
            {73, "Warum hat der Entwickler den Berg bestiegen? Für eine bessere 'View'."},
            {74, "Wie nennt man eine Gruppe von Programmierern? Ein 'Array'."},
            {75, "Warum war die Cloud so glücklich? Wegen der vielen 'Server'-Komplimente."},
            {76, "Was ist der Lieblings-Feiertag eines Programmierers? Der 'Tag der Arbeit' (weil dann niemand stört)."},
            {77, "Warum sind Programmierer wie Vampire? Sie arbeiten nachts und fürchten das Sonnenlicht (oder Meetings)."},
            {78, "Was sagt ein Programmierer beim Angeln? 'Catch of the day!'"},
            {79, "Warum war das Array so arrogant? Weil es 'indexiert' war."},
            {80, "Was ist das Lieblings-Auto eines Programmierers? Ein 'Ford Focus' (auf den Code)."},
            {81, "Warum hat der Programmierer eine Pflanze auf dem Schreibtisch? Für 'Root'-Zugriff."},
            {82, "Wie nennt man einen traurigen JavaScript-Fehler? Ein 'TypeError'."},
            {83, "Warum war der Debugger so gut im Basketball? Er konnte jeden 'Breakpoint' setzen."},
            {84, "Was ist der Lieblings-Snack eines Webentwicklers? 'Cookies' und 'Cache'."},
            {85, "Warum hat der Programmierer den Ozean überquert? Um zur anderen 'Seite' zu gelangen."},
            {86, "Was ist das Motto eines faulen Programmierers? 'Don't repeat yourself' (DRY) - also kopiere ich einfach."},
            {87, "Warum war die Variable so verwirrt? Wegen der vielen 'Zuweisungen'."},
            {88, "Was ist das Lieblings-Brettspiel eines Programmierers? 'Stack Overflow'."},
            {89, "Warum hat der Programmierer den Kühlschrank geöffnet? Um zu sehen, ob 'null' drin ist."},
            {90, "Wie nennt man einen Programmierer, der ständig Kaffee trinkt? Einen 'Java'-Junkie."},
            {91, "Warum war der Code so langsam? Er hatte zu viele 'Abhängigkeiten'."},
            {92, "Was ist das Lieblings-Restaurant eines Programmierers? 'Stack House'."},
            {93, "Warum hat der Entwickler immer Kopfhörer auf? Wegen der 'Background-Prozesse'."},
            {94, "Wie nennt man einen Fehler, den nur ein Programmierer versteht? Einen 'Bug'."},
            {95, "Warum war der Algorithmus so geheimnisvoll? Er hatte zu viele 'private' Methoden."},
            {96, "Was ist das Lieblings-Outfit eines Programmierers? Ein T-Shirt mit einem nerdy Spruch."},
            {97, "Warum hat der Programmierer seine Tastatur mit ins Bett genommen? Er wollte von Code träumen."},
            {98, "Wie nennt man einen glücklichen Programmierer? Einen Mythos."},
            {99, "Warum war das Framework so hilfreich? Es bot gute 'Unterstützung'."},
            {100, "Was ist der Lieblings-Planet eines Programmierers? Mars (wegen der Rover-Software)."},
            {101, "Warum hat der Programmierer den Marathon abgebrochen? Er ist in eine 'Endlosschleife' geraten."},
            {102, "Was ist der Lieblings-Kaffee eines Programmierers? Syntax Sugar."},
            {103, "Warum hat der Entwickler immer einen Notizblock dabei? Für 'Pseudocode'."},
            {104, "Wie nennt man einen Programmierer im Fitnessstudio? Einen 'Full-Stack'-Entwickler."},
            {105, "Warum war die API so gesprächig? Sie hatte viele 'Endpunkte'."},
            {106, "Was ist das Lieblings-Wetter eines Programmierers? 'Cloudy' mit Aussicht auf 'Server'."},
            {107, "Warum hat der Programmierer den Kochkurs abgebrochen? Zu viele 'Exceptions' beim Kochen."},
            {108, "Wie nennt man eine Katze, die gerne programmiert? Eine 'Kit-Hub'."},
            {109, "Warum war der Code so schwer zu debuggen? Er war 'verschlüsselt'."},
            {110, "Was ist das Lieblings-Märchen eines Programmierers? 'Alice im Wunderland' (wegen der rekursiven Logik)."},
            {111, "Warum hat der Programmierer eine Brücke gebaut? Um 'Interfaces' zu verbinden."},
            {112, "Wie nennt man einen Programmierer, der gerne gärtnert? Einen 'Root'-Benutzer."},
            {113, "Warum war der Computer so müde? Er hatte zu viele 'Tasks'."},
            {114, "Was ist das Lieblings-Musical eines Programmierers? 'Hamilton' (wegen der 'Callbacks')."},
            {115, "Warum hat der Entwickler den Kuchen nicht gegessen? Er war 'binary large object' (BLOB)."},
            {116, "Wie nennt man einen Fisch, der programmiert? Einen 'Code-Fish'."},
            {117, "Warum war der Programmierer so gut im Jonglieren? Wegen der 'Multithreading'-Erfahrung."},
            {118, "Was ist das Lieblings-Gemüse eines Programmierers? 'Root'-Beete."},
            {119, "Warum hat der Code eine Therapie gemacht? Er hatte 'Identitätsprobleme'."},
            {120, "Wie nennt man einen Programmierer, der immer die Wahrheit sagt? Einen 'Boolean'."},
            {121, "Warum war der Entwickler so gut im Verhandeln? Er kannte alle 'Protokolle'."},
            {122, "Was ist das Lieblings-Hobby eines Programmierers neben dem Programmieren? Noch mehr programmieren."},
            {123, "Warum hat der Programmierer den Fluss überquert? Um auf die 'andere Seite' des Codes zu gelangen."},
            {124, "Wie nennt man einen nervösen Programmierer? Einen 'Jitter'-Bug."},
            {125, "Warum war der String so anhänglich? Er wollte 'konkateniert' werden."},
            {126, "Was ist das Lieblings-Werkzeug eines Programmierers (außer dem Computer)? Ein Whiteboard."},
            {127, "Warum hat der Entwickler den Geist gerufen? Um 'Legacy Code' zu verstehen."},
            {128, "Wie nennt man einen Programmierer, der gerne reist? Einen 'Roam'-Entwickler."},
            {129, "Warum war der Compiler so streng? Er mochte keine 'Fehler'."},
            {130, "Was ist das Lieblings-Dessert eines Programmierers? Ein 'Apple Pi'."},
            {131, "Warum hat der Programmierer aufgehört, Poker zu spielen? Zu viele 'Bluffs' im Code gesehen."},
            {132, "Wie nennt man einen Programmierer, der Witze erzählt? Einen 'Com-pile-dian'."},
            {133, "Warum war der Code so emotional? Er hatte zu viele 'Ausdrücke'."},
            {134, "Was ist das Lieblings-Spiel eines Programmierers in der Spielhalle? 'Pac-Man' (wegen der Pfadfindung)."},
            {135, "Warum hat der Entwickler eine Sonnenbrille getragen? Wegen des 'hellen' Bildschirms."},
            {136, "Wie nennt man einen Programmierer, der Detektiv spielt? Sherlock Ohms."},
            {137, "Warum war die Funktion so egoistisch? Sie hat immer nur 'return' für sich selbst gemacht."},
            {138, "Was ist das Lieblings-Getränk eines Quantenprogrammierers? Ein Qubit-Ale."},
            {139, "Warum hat der Programmierer den Baum umarmt? Um die 'Knoten' zu spüren."},
            {140, "Wie nennt man einen Programmierer, der schlecht gelaunt ist? Einen 'Source'-Pott."},
            {141, "Warum war die Datenbank so ordentlich? Wegen der 'Normalisierung'."},
            {142, "Was ist das Lieblings-Zitat eines Programmierers? 'There's no place like 127.0.0.1'."},
            {143, "Warum hat der Entwickler den Ball geworfen? Um eine 'Exception' auszulösen."},
            {144, "Wie nennt man einen Programmierer, der schnell tippt? Einen 'Keyboard Warrior'."},
            {145, "Warum war der Code so schwer zu verstehen? Er war zu 'abstrakt'."},
            {146, "Was ist das Lieblings-Geräusch eines Programmierers? Das Klicken der Tastatur."},
            {147, "Warum hat der Programmierer den Fernseher repariert? Er hat einen 'Bug' im System gefunden."},
            {148, "Wie nennt man einen Programmierer, der gerne singt? Einen 'Code-Tenor'."},
            {149, "Warum war das Objekt so verwirrt? Wegen der 'Polymorphie'."},
            {150, "Was ist der Unterschied zwischen einem Software-Update und einem Wunder? Ein Wunder passiert nur einmal."}
        };

        internal static string GetRandomProgrammingJoke()
        {
            if (ProgrammingJokesDic.Count == 0)
            {
                return "How did u get here? " + (autismCounter < Int32.MaxValue ? ++autismCounter : "Bro es reicht...");
            }
            int randomIndex = random.Next(1, ProgrammingJokesDic.Count + 1);
            string currentJoke;
            if (!ProgrammingJokesDic.TryGetValue(randomIndex, out string? value))
            {
                randomIndex = ProgrammingJokesDic.First().Key;
                currentJoke = ProgrammingJokesDic.First().Value;
            }// Gibt den ersten Witz zurück, falls der zufällige Index nicht existiert
            else currentJoke = value;
                ProgrammingJokesDic.Remove(randomIndex); // Entfernt den Witz, um Duplikate zu vermeiden
            return currentJoke;
        }
    }
}
